### PR TITLE
连接am335x_pru_package

### PR DESCRIPTION
**Pull request by abc838**
连接am335x_pru_package

### CODE REVIEW

**Comment by jadonk** [comment]
Too many changes at once and it needs to be rebased as well. Please rebase, break it down into smaller chunks and resubmit.

**Comment by jadonk** [comment]
@modmaker @abc838 Can you rebase these commits? These changes look valuable.

**Comment by cdsteinkuehler** [comment]
@jadonk sadly, @modmaker is no longer with us (he passed away), but I would like to see these changes included in the pasm shipped with the 'Bone.  They are required for the code I wrote for Machinekit.

Besides rebasing, how small of chunks are you looking for?

**Comment by cdsteinkuehler** [comment]
This PR can be closed.
I have reviewed modmaker's changes and support for the new instructions is already in the master branch of this repo.  My initial tests with this version of pasm failed because the structure name comparisons were case insensitive in modmaker's version but are case-sensitive in this version.  Once I fixed up my case issues, I was able to generate bit-identical output from both versions.

**Pull request closed without merging**
